beangulp/__init__.py
beangulp/extract.py
beangulp/extract_test.py
beangulp/file.py
beangulp/file_test.py
beangulp/identify.py
beangulp/identify_test.py
beangulp/scripts_utils.py
beangulp/test_utils.py

This it the first step toward the goal of providing an easily
customizable and extensible framework with integrate testing
facilities for importers.  The old ``beancount.ingest`` API is
preserved under the ``beangulp`` namespace, however the CLI is
modernize and improved.  Further changes are expected.  The
autogenerated command line help text (see ``--help`` command line
option to the main scritp and to the sub-commands) should be enough to
understand how to use it.  Extended documentation will follow.

Use Click for command line arguments parsing

---

beangulp/cache.py
examples/office/importers/acme/acme_pdf.py
tests/test_cache.py

This is still missing documentation, but I know that @blais is eagerly waiting for something like this, thus this early PR to review. There are example of usage in the added tests. By default the cache is keyed on the filename and expired on the file modification time. However, this can be overwritten with the `key` argument to the cache decorator. In the tests there is an example for using the input file SHA1 digest. All arguments to the decorated function are always part of the cache key.
Which directory to use for the cache on WIndows? On Unix-like systems `~/.cache/beangulp/` is a good choice, but I don't have idea what would be the equivalent on Windows. Also, what should be the behavior when the cache directory does not exist? The implementation proposed simply raises …

cache: Add disk cache decorator

---

beangulp/testing.py

Click does not checke the $TERM environment variable to decide whether
to emit color escape sequences as it is customarily done. This results
in the escape sequences emitted for example when the testing framework
is invoked within Emacs compilation mode. Do the check in our logging
wrapper.
Fixes #36.

testing: Disable colors on dumb terminals

---

beangulp/testing.py

DeprecationWarnings are ignored by default. It makes sense for a test
runner to implicitly enable all warnings when running tests. The test
runner provided by the unittest module does this. This can be
overridden with the -W command line option of the Python interpreter.

testing: Print DepreactionWarnings when running the tests

---

examples/importers/ofx.py

There is no need to have the account in the importer name. Keep the
same format for the importer name as the other examples importers.

examples/ofx: Remove name method

---

beangulp/mimetypes.py

Associate .beancount and .beans extensions to text/beancount MIME type.

mimetypes: Add text/beancount to the recognized MIME types.

---

requirements.txt
setup.cfg

This was forgotten when the command line interface was ported to use
Click for command line argument parsing. The library is installed as a
dependency of beancount so things were working anyhow.

setup: Add click library to dependencies

---

beangulp/cache_test.py

Obliously Python source files do not have an official MIME type and
apparently different versions of libmagic are more or less good in
determining the MIME type.

tests: Fix MIME type detection test on macOS with libmagic 5.39

---

beangulp/cache.py
beangulp/cache_test.py

Fix file head byte data decoding when the byte string read from the
file terminates in the middle of an unicode character represented by
more than one byte. This is likely to occur for vaiable width
encodings such as utf8 with languages that uses characters beyond the
ascii set.
FileMemo is deprecated, but it should work correcly as long as it exists.
Fixes #7.

cache: Fix FileMemo.head() unicode decoding

---

.github/workflows/install.yaml
.pylintrc
beangulp/__init__.py
beangulp/archive.py
beangulp/archive_test.py
beangulp/extract.py
beangulp/extract_test.py
beangulp/identify.py
beangulp/identify_test.py
beangulp/importer.py
beangulp/similar.py
beangulp/testing.py
beangulp/tests/archive.rst
beangulp/tests/extract.rst
beangulp/tests/identify.rst
beangulp/tests/utils.py
examples/importers/acme.py
examples/importers/ofx.py
examples/importers/utrade.py
examples/ledger/ledger.import

This is a proposal for a new Import interface.
Compared to the existing interface it
- drops the use of the memory cache,
- changes `name` from a function to an attribute (implemented as a property, in the base class),
- renames some of the methods,
- adds the `sortkey` static method and the `sort()` and `filter()` methods.
The `sortkey()` static method is used by the base class implementation of the `sort()` method in the obvious way. The `sort()` method allows to customize sorting of the entries extracted by the importer, defaulting to the current sorting. The `filter()` method allows to post-process the extracted entries, for example to plug in auto categorization of transactions.
I am debated whether an explicit `deduplicate()` method, maybe using  `cmp()` method under the hood, …

New Importer interface

---

beangulp/file_type_test.py
beangulp/importer_test.py
beangulp/importers/config_test.py
beangulp/importers/csv.py
beangulp/importers/csv_test.py
beangulp/importers/fileonly_test.py
beangulp/similar_test.py
examples/importers/tests/test_ofx.py

This is prompt by an issue with the import of the standard library
csv module when executing beangulp/importers/csv_test.py as a script:
it fails because in this case sys.path is extended with the location
of the test script which contains a csv module that shadows the
standard library one.
Both unittest and pytest allow to easily load tests from specific
modules, which is a better solution than making each test module a
standalone script. For example, it allows to use relative import
paths.

tests: Make all tests not executable as scripts

---

.github/workflows/install.yaml
.pylintrc
beangulp/importers/csvbase.py
examples/importers/newcsvbank.py

I was looking at cleaning up the CSV importer and adapt it to the new importer interface and I got tired of how untidy the code looks, so I came up with this alternative approach for providing a generic CSV importer.
Instead than providing a class with many parameters to control every aspect of the ingestion process, this takes the approach of providing a base class that can be easily extended to process arbitrary CSV files.
This does not implement any auto-discovery feature as it is much easier and less error prone to have the data processing parameters clearly encoded in the importer and the structure of the imported data should not change over time.
I find it much nicer but I may have missed some important use cases that cannot be supported or are hard to support in this way. Please …

importers/csvbase: New approach for a generic CSV importer

---

beangulp/importers/csv.py
beangulp/importers/csv_test.py

Note: I don't like this; I really don't like inheritance. I'd like to replace all my
CSV importers by a petl + single-function setup. But I need to port a whole
bunch of them now and this at least allow me to modernize our configurations
without doing a lot of work.
BTW this is achieved using a base class and should remain compatible with existing importers.

Ported the legacy CSV importer to use the newer interface.

---

beangulp/importers/mixins/identifier.py

Do not raise an exception when MIME type cannot be determined.

Fix identifier mixing

---

beangulp/__init__.py
beangulp/extract.py
beangulp/extract_test.py
beangulp/similar.py
examples/import.py

Two small commits on top of #58. @blais I think I found why deduplication does not work reliably for you. See commit 45bcdf0. Commit d81fa2b extends the deduplication mechanism to work for entries within the same extract run as proposed in #9. Despite my initial schepticism, I think the algorithm I found makes a lot of sense.

Fix and extend deduplication

---

beangulp/__init__.py
examples/importers/ofx.py

Ensure that we will accept the non-strict type we added, and don't try to match a tuple against a string. Without this, type check will always fail, and no files will pass identification.

Fix MIME type check for example OFX importer.

---

beangulp/__init__.py

I'm using a shell script to automatically extract and archive files , and I'm using the -q flag in `extract` to suppress unnecessary printing. I realized that a such flag doesn't exist for `archive`. I implemented it by copying code from the `_extract`-function to the `_archive`-function

archive: Add --quiet option

---

examples/README.md

I tried to reproduce the example but stumbled with the currently available documentation. Perhaps the example can be split into a separate repository with a minimal TL;DR? Anyway, I added the minimal necessary steps to reproduce the example in Linux to the example `Readme.md`. Maybe this helps some new people.

docs: improve example by providing TL;DR

---

.github/workflows/install.yaml

This is being done also to support PEP585 type annotations.

ci: upgrade oldest version to match upstream version

---

.github/workflows/test.yaml
pyproject.toml

Testing with Python 3.7 is becoming increasingly difficult because actions/install-python dropped support for it. Python 3.7 is EOL since 2023-06-27: there is very little value in keeping supporting it.

build, ci: Drop support for Python 3.7

---

beangulp/importers/csvbase.py
beangulp/importers/csvbase_test.py

This PR fixes a bug where the the wrong balance assertion was picked for CSV with entries in date ascending order. For a little more context, see https://github.com/beancount/beangulp/issues/145.
I've added a test to catch future regressions.

Fix wrong balance being added for csvbase importers when csv file is in date ascending order

---

beangulp/importers/csv.py

The named keyword arguments in the (v2 legacy) `beangulp.importers.csv.Importer` do not seem to get passed to the parent class in the `__init__` method.  This can lead to unexpected behavior (for instance, I set `invert_sign` to `True`, but it was silently ignored).  To fix this, we supply the keyword arguments to the call to `super().__init__`.

Fix keyword args in legacy CSV Importer

---

beangulp/importers/csvbase.py
beangulp/importers/csvbase_test.py

it helps to exclude some records. 
Please let me know if there is a better way to do that. :D

make 'finialize' can remove current record

---

beangulp/importers/csvbase.py
beangulp/importers/csvbase_test.py

This is useful to parse statements where credit (positive amounts) and debits (negative amounts) are placed in different columns.

importers.csvbase: Add CreditOrDebit column type

---

beangulp/importers/config_test.py
beangulp/importers/csvbase.py

Today when I batch import two years of statements for a rarely-used account, I find this auto detection of row order might produce incorrect results.
For example, there is only one transaction in January:
```
2023-01-31,...
```
... and four transactions in February:
```
2023-02-28,...
2023-02-20,...
2023-02-11,...
2023-02-05,...
```
When processing the January file, the code auto-detects the order as `ASCENDING` as there is only one transaction, and for _Feburary and any subsequent files_, the code no longer tries to detect the order because `self.order` is already set. But this bank actually uses `DESCENDING` order for their files.
This error might be masked if the entries are eventually sorted. But I disabled sorting for some other reason so I hit this edge case.

fix(csvbase): do not persist auto-detected self.order

---

beangulp/__init__.py
beangulp/archive.py
beangulp/extract.py
beangulp/identify.py

Hi I learned how to write my own importers by reading the code (btw it was intuitive).
These changes are by-products but I thought they may help others too.

add type annotations in beangulp identify/extract/archive

---

LICENSE

The Free Software Foundation is now remote-only, and no longer has a physical mailing address. This PR updates `LICENSE` with the latest text from https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.

Update GPLv2 text for remote-only FSF

---

pyproject.toml

This further clarifies the license and shuts up a setuptools warning.

pyproject: Adopt License-Expression (PEP 639)
